/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cyber.cafe.management;
import java.sql.*;
import javax.swing.*;
import dao.userDao;
import model.*;
import co.yogesh.Captcha;
import java.awt.Color;
import dao.userDataDao;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author sai tarun
 */
public class Loginpage extends javax.swing.JFrame {
    public String emailPattern = "^(.+)@(.+)$";
    Captcha cap =new Captcha();
     public static String Name;
     public static String passs;
     public static String e;

    /**
     * Creates new form Loginpage
     */
    public Loginpage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        btnLogin.setEnabled(false);
       this.setLocationRelativeTo(null);
        cap.setImageCaptcha(captcha);
    btnverify.setEnabled(true);
    
    }
    
    
    
    public void clear(){
    txtEmail.setText("");
    txtpassword.setText("");
    btnLogin.setEnabled(false);
     
    }
    
 private void validate1(){
     String Email = txtEmail.getText();
  if (    txtpassword.getPassword().length==0 || !Email.matches(emailPattern)   ){
           btnverify.setEnabled(false); }
  else{  btnverify.setEnabled(true);}
      }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        captcha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnverify = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnForgotPassword = new javax.swing.JButton();
        lsignUP = new javax.swing.JLabel();
        adminlogin = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PngItem_5238950.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, 30));
        getContentPane().add(captcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 138, 49));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 40));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 240, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 349, 37, -1));

        btnverify.setText("verify");
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        btnForgotPassword.setText("Forgot Password");
        getContentPane().add(btnForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        lsignUP.setForeground(new java.awt.Color(255, 255, 255));
        lsignUP.setText("sign up?");
        lsignUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsignUPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lsignUPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lsignUPMouseExited(evt);
            }
        });
        getContentPane().add(lsignUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 59, -1));

        adminlogin.setForeground(new java.awt.Color(255, 255, 255));
        adminlogin.setText("Admin login?");
        adminlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminloginMouseExited(evt);
            }
        });
        getContentPane().add(adminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 84, -1));

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 240, 30));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Browse Internet Cafe");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 830, 140));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1355, 10, 100, 50));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 390, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaperflare.com_wallpaper (3).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String Email = txtEmail.getText();   // Collecting the input
       String Password = txtpassword.getText();
       this.passs= Password;
        user1 User =null;
        User =userDao.login(Email,Password);
           if(txtEmail.getText().length()==0){  // Checking for empty field
               
               JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");}
   else if(txtpassword.getPassword().length==0){  // Checking for empty field
                
       JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");}
   else {if(User == null){
          JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");}
   
   else{
          JOptionPane.showMessageDialog(null, "Correct Login Credentials");
       try {
           Name  = userDataDao.login2(Email, Password);
           e =txtEmail.getText();
       } catch (SQLException ex) {
           Logger.getLogger(Loginpage.class.getName()).log(Level.SEVERE, null, ex);
       }
    dispose();
   new Dashboard().setVisible(true);
   new Dashboard().setAlwaysOnTop(true);
}}        


    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validate1();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        // TODO add your handling code here:
                if(cap.Validate (captcha,jTextField1.getText())){
                JOptionPane.showMessageDialog(this, "Captcha matched");
                btnLogin.setEnabled(true);}
        else {
            JOptionPane.showMessageDialog(this, "Captcha does not match");
                btnLogin.setEnabled(false);
                captcha.setText("");}

    }//GEN-LAST:event_btnverifyActionPerformed

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        // TODO add your handling code here:
        validate1();
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void lsignUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsignUPMouseClicked
        // TODO add your handling code here:
        dispose();
        new signup().setVisible(true);
    }//GEN-LAST:event_lsignUPMouseClicked

    private void lsignUPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsignUPMouseEntered
        // TODO add your handling code here:
        lsignUP.setForeground(Color.BLUE);
    }//GEN-LAST:event_lsignUPMouseEntered

    private void lsignUPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsignUPMouseExited
        // TODO add your handling code here:
         lsignUP.setForeground(Color.WHITE);
    }//GEN-LAST:event_lsignUPMouseExited

    private void adminloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminloginMouseClicked
        // TODO add your handling code here:
        dispose();
        new adminLogin().setVisible(true);
    }//GEN-LAST:event_adminloginMouseClicked

    private void adminloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminloginMouseEntered
        // TODO add your handling code here:
        adminlogin.setForeground(Color.BLUE);
    }//GEN-LAST:event_adminloginMouseEntered

    private void adminloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminloginMouseExited
        // TODO add your handling code here:
        adminlogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_adminloginMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Confirm Exit","LogOut",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {int a =0;
            System.exit(a);}
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminlogin;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnverify;
    private javax.swing.JLabel captcha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lsignUP;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
        }