/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cyber.cafe.management;

import javax.swing.JOptionPane;
import model.user1;
import dao.userDao;
import java.awt.Color;
import static java.lang.Math.round;
import javax.swing.JFrame;
import java.util.Random;
import model.EmailUtil;
import model.SSLEmail;
 import model.user1;

/**
 *
 * @author sai tarun
 */
public class signup extends javax.swing.JFrame {
   
    public String a; 
    public String EMAILPattern ="^(.+)@(.+)$";
    public String MOBILENUMBERPattern= "(0/91)?[7-9][0-9]{9}";
    //"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2, 4}$" "^(.+)@(.+)$""^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$"
    //"(0/91)?[7-9][0-9]{9}""^[0-9]*$"
    
    
    
    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        btnSave1.setEnabled(false);
      setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void clear(){
    txtNAME.setText("");
    txtEMAIL.setText("");
    txtMOBILENUMBER.setText("");
    txtADDRESS.setText("");
    txtPASSWORD.setText("");
    txtotp.setText("");
    btnSave1.setEnabled(false);
    }
    
    public void validateFields(){
      String name = txtNAME.getText();
      String email = txtEMAIL.getText();
      String mobileNumber = txtMOBILENUMBER.getText();
      String address = txtADDRESS.getText();
      String password = txtPASSWORD.getText();
      if(!name.equals("") && email.matches(EMAILPattern) && mobileNumber.matches(MOBILENUMBERPattern)&& mobileNumber.length()== 10 && !address.equals("") && !password.equals("")){
      btnSave1.setEnabled(true);}
      else{
      btnSave1.setEnabled(false);}
    }
    
    public String generater(){
        Random rand = new Random();
        double r =  ((Math.random()*(9999-1000))+1000);
        int d = (int) round(r);
         String otp = d +"";
        return otp;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEMAIL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNAME = new javax.swing.JTextField();
        txtMOBILENUMBER = new javax.swing.JTextField();
        txtADDRESS = new javax.swing.JTextField();
        txtPASSWORD = new javax.swing.JPasswordField();
        btnSave1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnToLogin = new javax.swing.JButton();
        txtotp = new javax.swing.JTextField();
        btnverify = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnsendOTP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEMAIL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEMAILKeyReleased(evt);
            }
        });
        getContentPane().add(txtEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 230, 261, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 142, 87));

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 101, -1));

        jLabel4.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 275, -1, -1));

        jLabel3.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 109, -1));

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 80, -1));

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, -1, -1));

        txtNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMEActionPerformed(evt);
            }
        });
        txtNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNAMEKeyReleased(evt);
            }
        });
        getContentPane().add(txtNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 261, -1));

        txtMOBILENUMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMOBILENUMBERKeyReleased(evt);
            }
        });
        getContentPane().add(txtMOBILENUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 261, -1));

        txtADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADDRESSActionPerformed(evt);
            }
        });
        txtADDRESS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtADDRESSKeyReleased(evt);
            }
        });
        getContentPane().add(txtADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, 261, -1));

        txtPASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPASSWORDKeyReleased(evt);
            }
        });
        getContentPane().add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 350, 261, -1));

        btnSave1.setBackground(new java.awt.Color(0, 0, 0));
        btnSave1.setFont(new java.awt.Font("Monospac821 BT", 1, 18)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(255, 255, 255));
        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save12.png"))); // NOI18N
        btnSave1.setText("save");
        btnSave1.setBorderPainted(false);
        btnSave1.setContentAreaFilled(false);
        btnSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSave1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSave1MouseExited(evt);
            }
        });
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, 120, 50));

        btnClear.setFont(new java.awt.Font("Monospac821 BT", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reset.png"))); // NOI18N
        btnClear.setText("Reset");
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 430, -1, -1));

        btnToLogin.setFont(new java.awt.Font("Monospac821 BT", 1, 18)); // NOI18N
        btnToLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bachbtn2.png"))); // NOI18N
        btnToLogin.setText("Back to Login");
        btnToLogin.setContentAreaFilled(false);
        btnToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnToLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnToLoginMouseExited(evt);
            }
        });
        btnToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 440, -1, -1));

        txtotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotpActionPerformed(evt);
            }
        });
        getContentPane().add(txtotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 260, -1));

        btnverify.setFont(new java.awt.Font("Monospac821 BT", 0, 18)); // NOI18N
        btnverify.setForeground(new java.awt.Color(255, 255, 255));
        btnverify.setText("VERIFY");
        btnverify.setContentAreaFilled(false);
        btnverify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnverifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnverifyMouseExited(evt);
            }
        });
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("enter otp");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        btnsendOTP.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnsendOTP.setForeground(new java.awt.Color(255, 255, 255));
        btnsendOTP.setText("SEND OTP");
        btnsendOTP.setContentAreaFilled(false);
        btnsendOTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsendOTPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsendOTPMouseExited(evt);
            }
        });
        btnsendOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendOTPActionPerformed(evt);
            }
        });
        getContentPane().add(btnsendOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 230, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\sai tarun\\Downloads\\final cancelbutton.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 0, 30, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg12345.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1720, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMEActionPerformed
        // TODO add your handling code here:
       // validateFields();
    }//GEN-LAST:event_txtNAMEActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        user1 User = new user1();
        User.setNAME(txtNAME.getText());
        User.setEMAIL(txtEMAIL.getText());
        User.setMOBILENUMBER(txtMOBILENUMBER.getText());
        User.setADDRESS(txtADDRESS.getText());
        User.setPASSWORD(txtPASSWORD.getText());
        userDao.save(User);
        clear();
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNAMEKeyReleased
        // TODO add your handling code here:
      validateFields();
    }//GEN-LAST:event_txtNAMEKeyReleased

    private void txtEMAILKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEMAILKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEMAILKeyReleased

    private void txtMOBILENUMBERKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMOBILENUMBERKeyReleased
        // TODO add your handling code here:
       validateFields();
    }//GEN-LAST:event_txtMOBILENUMBERKeyReleased

    private void txtADDRESSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtADDRESSKeyReleased
        // TODO add your handling code here:
       validateFields();
    }//GEN-LAST:event_txtADDRESSKeyReleased

    private void txtPASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPASSWORDKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtPASSWORDKeyReleased

    private void txtADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADDRESSActionPerformed
        // TODO add your handling code here:
        //validateFields();
    }//GEN-LAST:event_txtADDRESSActionPerformed

    private void btnToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Loginpage().setVisible(true);
    }//GEN-LAST:event_btnToLoginActionPerformed

    private void btnSave1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSave1MouseEntered
        // TODO add your handling code here:
         btnSave1.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnSave1MouseEntered

    private void btnSave1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSave1MouseExited
        // TODO add your handling code here:
        btnSave1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSave1MouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        btnClear.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnToLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToLoginMouseEntered
        // TODO add your handling code here:
        btnToLogin.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnToLoginMouseEntered

    private void btnToLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToLoginMouseExited
        // TODO add your handling code here:
        btnToLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnToLoginMouseExited

    private void btnverifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifyMouseEntered
        // TODO add your handling code here:
        btnverify.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnverifyMouseEntered

    private void btnverifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifyMouseExited
        // TODO add your handling code here:
        btnverify.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnverifyMouseExited

    private void btnsendOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendOTPActionPerformed
        // TODO add your handling code here:
       SSLEmail ap = new SSLEmail();
       String a =generater();
       this.a=a;
       if (!txtEMAIL.equals("")){
    JOptionPane.showMessageDialog(null, "OTP is sent");
     ap.message(txtEMAIL.getText(),this.a );
    }
       else{JOptionPane.showMessageDialog(null, "Please enter valid Email!");}
    }//GEN-LAST:event_btnsendOTPActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        // TODO add your handling code here:
        if (a.equals(txtotp.getText())){
        btnSave1.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Email is Verified");}
        else{btnSave1.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Please enter correct OTP");}
    }//GEN-LAST:event_btnverifyActionPerformed

    private void btnsendOTPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsendOTPMouseEntered
        // TODO add your handling code here:
        btnsendOTP.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnsendOTPMouseEntered

    private void btnsendOTPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsendOTPMouseExited
        // TODO add your handling code here:
        btnsendOTP.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnsendOTPMouseExited

    private void txtotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotpActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnToLogin;
    private javax.swing.JButton btnsendOTP;
    private javax.swing.JButton btnverify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtADDRESS;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtMOBILENUMBER;
    private javax.swing.JTextField txtNAME;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables

   
}
